Ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', include('product.urls')),
	url(r'^login/', include('login.urls', namespace="login")),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.conf.urls import include,url
from .views import *

urlpatterns = [
    
    url(r'^$', user_register,name='user_register'),
    url(r'^user_login/$', user_login, name='user_login'),
    
    ]                  

product/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import *

urlpatterns = [
    url(r'^$', index, name='index'),
	url(r'^category/(\w+)/$',product_category,name='category'),
	url(r'^detail/(\d+)/$',detail,name='detail'),
	
	url(r'^cartinfo/$', cart_detail,name='cartinfo'),
	url(r'^cartinfo/(\d+)/$', delete_product,name='delete_product'),
]

login/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserRegister(models.Model):
	user=models.OneToOneField(User)
	address=models.CharField(max_length=50)	
	city=models.CharField(max_length=50)
	image=models.FileField(upload_to='pic')
	
	def __unicode__(self):
		return self.user.username

product/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Categories(models.Model):
	name=models.CharField(max_length=100)
	slug=models.SlugField(max_length=100)
	
	def __unicode__(self):
		return self.name
		
class Product(models.Model):
	category=models.ForeignKey(Categories)
	name=models.CharField(max_length=100)
	slug=models.SlugField(max_length=100,null=True)
	description=models.TextField(blank=True)
	pic=models.FileField(upload_to='pic',null=True)
	price=models.DecimalField(max_digits=10,decimal_places=2)
	
	def __unicode__(self):
		return self.name
		
class Cart(models.Model):
	product=models.ForeignKey(Product)
	quantity=models.IntegerField()
	
	def product_price(self,q,price):
		return q*price
	

login/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *

class MyForm(forms.ModelForm):
	
	address= forms.CharField(max_length=50, required=False)
	city= forms.CharField(max_length=50)
	image=forms.FileField()
	
	class Meta:
		model=User
		fields=['username','email','password','address','city','image']
		

product/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1,21)]

class CartForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

class NewCart(forms.ModelForm):
	class Meta:
		model=Cart
		fields=['quantity']

class UserForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput)
	
	class Meta:
		model=User
		fields=['username','email','password']
		

login/views.py
from django.shortcuts import render
from django.http import *
from django.contrib import auth
from .forms import *
from .models import *


# Create your views here.
#def index(request):
#	info=UserRegister.objects.all()
#	return render(request,'home.html',{'info':info})

def user_register(request):
	if request.method=='POST':
		form=MyForm(request.POST,request.FILES)
		if form.is_valid():
			cd=form.cleaned_data
			obj=User(username=cd['username'],email=cd['email'])
			
			obj.save()
			UserRegister.objects.create(user=obj, address=cd['address'],city=cd['city'], image=cd['image'])
			
			return HttpResponseRedirect('/')
			
	else:
		form = MyForm()
	
	
	return render(request,'login/payment.html',{'form':form})

def user_login(request):
		
	if request.method=='POST':
		username=request.POST['username']
		password=request.POST['password']
		user=auth.authenticate(username=username, password=password)
		
		if user is not None:
			auth.login(request,user)
			return HttpResponseRedirect('/login/')
		else:
			return HttpResponseRedirect('/login/')
	
	return render(request, 'login/login.html')
			# Create your views here.

product/views.py
from django.shortcuts import render
from django.http import *
from .models import *
from .forms import *
# Create your views here.

def index(request):
	cat=Categories.objects.all()
	template='product/home.html'
	content={
		'title':'All Products',
		'category':cat
	}
	return render(request, template, content)
	
def product_category(request,n):
    all_prod=Categories.objects.get(slug=n)
    categories=Categories.objects.all()
    return render(request,'product/product_category.html',{'category':all_prod,'categories':categories})

	
'''def detail1(request,d,slug):
    cart=Cart(request)
    #product=Product.objects.get(slug=slug)
    product = get_object_or_404(Product, id=d, slug=slug)
	if request.method=='POST':
		cartform=CartForm(request.POST)
		if cartform.is_valid():
			cd=cartform.cleaned_data
			cart.add(product=product,quantity=cd['quantity'],
			update_quantity=cd['update'])

			return redirect('cart:cart_detail')

    else:
        cartform=CartForm()
        
    return render(request,'product/detail.html',{'prod':product,'cartform':cartform})
'''
def detail(request, id):
	product=Product.objects.get(id=id)
	
	if request.method=='POST':
		form=NewCart(request.POST)
		if form.is_valid():
			f=form.save(commit=False)
			f.product=product
			f.save()
			return HttpResponseRedirect('/cartinfo/')
					
	else:
		form=NewCart()
		content={
			'title':'Product Form',
			'form':form,
			'product':product
			
		}
	return render(request,'product/detail_product.html', content)
		
def cart_detail(request):
	cart_record=Cart.objects.all()
	#print cart_record.product_price(3,4)
	d=[]
	
	for c in cart_record:
		d.append(c.product.price*c.quantity)
	
	
	content={
		'title':'Cart Detail',
		'cart_detail':cart_record,
		'total':sum(d)
	}
	return render(request, 'product/cart_detail.html', content)
	
def delete_product(request,id):
	product=Cart.objects.get(id=id)
	product.delete()
	return HttpResponseRedirect('/cartinfo/')
	

login/templates/include/footer.html
<footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

login/templates/include/nav.html
{% block styles %}
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box}
/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 15px;
    margin: 5px 0 22px 0;
    display: inline-block;
    border: none;
    background: #f1f1f1;
}

/* Add a background color when the inputs get focus */
input[type=text]:focus, input[type=password]:focus {
    background-color: #ddd;
    outline: none;
}

/* Set a style for all buttons */
button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
    opacity: 0.9;
}

button:hover {
    opacity:1;
}

/* Extra styles for the cancel button */
.cancelbtn {
    padding: 14px 20px;
    background-color: #f44336;
}

/* Float cancel and signup buttons and add an equal width */
.cancelbtn, .signupbtn {
  float: left;
  width: 50%;
}

/* Add padding to container elements */
.container {
    padding: 16px;
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: #474e5d;
    padding-top: 50px;
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
}

/* Style the horizontal ruler */
hr {
    border: 1px solid #f1f1f1;
    margin-bottom: 25px;
}
 
/* The Close Button (x) */
.close {
    position: absolute;
    right: 35px;
    top: 15px;
    font-size: 40px;
    font-weight: bold;
    color: #f1f1f1;
}

.close:hover,
.close:focus {
    color: #f44336;
    cursor: pointer;
}

/* Clear floats */
.clearfix::after {
    content: "";
    clear: both;
    display: table;
}

/* Change styles for cancel button and signup button on extra small screens */
@media screen and (max-width: 300px) {
    .cancelbtn, .signupbtn {
       width: 100%;
    }
}
</style>
{% endblock %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
           
			
          </ul>
		  <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'login:user_register' %}"><span class="glyphicon glyphicon-user"></span>




	  <button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Sign Up</button>
	  
	  </a>
	  
	  <div id="id01" class="modal">
  <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
  <form class="modal-content" action="/action_page.php">
    <div class="container">
      <h1>Sign Up</h1>
      <p>Please fill in this form to create an account.</p>
      <hr>
      <label for="email"><b>Email</b></label>
      <input type="text" placeholder="Enter Email" name="email" required>

      <label for="psw"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" required>

      <label for="psw-repeat"><b>Repeat Password</b></label>
      <input type="password" placeholder="Repeat Password" name="psw-repeat" required>
      
      <label>
        <input type="checkbox" checked="checked" name="remember" style="margin-bottom:15px"> Remember me
      </label>

      <p>By creating an account you agree to our <a href="#" style="color:dodgerblue">Terms & Privacy</a>.</p>

      <div class="clearfix">
        <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
        <button type="submit" class="signupbtn">Sign Up</button>
      </div>
    </div>
  </form>
</div>
<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>

	  
	  
	  
	  
	  
	  
	  
	  
	  
	  
	  
	  
	  
	  
	  
	  
	  </li>
      <li><a href="{% url 'login:user_login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
	   <li >
              <div class="cart-icon" style="color:#fff">
			  <span class="cart-label badge" style="background-color:#e91e63;font-size:17px ;color:#ffcc80;">{{request.session.cart}}</span>
			  <br/>
			  <i class="fa fa-shopping-cart " style="font-size:25px"></i>
				</div>
            </li>
					
    </ul>
        </div>
      </div>
    </nav>

product/templates/include/footer.html
<footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

product/templates/include/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
           
			
          </ul>
		  <ul class="nav navbar-nav navbar-right">
      <li><a href="{% url 'login:user_register' %}"><span class="glyphicon glyphicon-user"></span>

Sign Up
	  
	  </a> 
	  
	  
	  </li>
      <li><a href="{% url 'login:user_login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
	   <li >
              <div class="cart-icon" style="color:#fff">
			  <span class="cart-label badge" style="background-color:#e91e63;font-size:17px ;color:#ffcc80;">{{request.session.cart}}</span>
			  <br/>
			  <i class="fa fa-shopping-cart " style="font-size:25px"></i>
				</div>
            </li>
					
    </ul>
        </div>
      </div>
    </nav>

product/templates/product/cart_detail.html
{% extends 'extends/base.html' %}
{% load staticfiles %}
{% load app_tags %}
{% block content %}
 <div class="row">

        <div class="col-lg-3">

          <h3 class="my-4">Cart Detail</h3>
          

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">

          <div class="row">
		  
		    
            <div class="col-lg-12 col-md-12 mb-12">
			
			
<table class="table ">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product Name</th>
        <th>Quantity</th>
		<th>Price</th>
		<th>Total</th>
		<th></th>
      </tr>
    </thead>
    <tbody>
	{% for i in cart_detail %}
      <tr>
        <td>{% if i.product.pic %}<img src="{{i.product.pic.url}}" class="avatar" height="100px" width="100px"/>{% endif %}</td>
        <td>{{i.product.name}}</td>
        <td>{{i.quantity}}</td>		
        <td>{{i.product.price}}</td>
		<td>{{i|cart_price}}</td>
		<td><a href="{% url 'delete_product' i.id %}"><button type="button" class="button btn btn-danger">Delete</button></a></td>
      </tr>
      {% endfor %}
	  <tr>
		<thead>
			
			<td></td>
			<td></td>
			<td></td>
			<th>Total Amount: </th>
			<td>{{total}}</td>
		</thead>
		
	  <tr>
	   <tr>
		<thead>
			
			<td></td>
			<td></td>
			<td>
			
			
					
			
			
			
			
			</td>
			<th></th>
			<td>
				<button type="button" class="button btn btn-success btn-md" data-toggle="modal" data-target="#myModal" onclick="document.getElementById('id01').style.display='block'" style="width:auto;"><span>Procced </span></button>
			
			

<div id="id01" class="modal">
  
  <form class="modal-content animate" action="{% url 'login:user_login' %}" method="post">
    {% csrf_token %}
	<div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
      <img src='{% static "img/img_avatar2.png" %}'alt="Avatar" class="avatar" height="1000px" width="1000px"/>
    </div>

    <div class="container">
      <label for="uname"><b>Username</b></label>
      <input type="text" placeholder="Enter Username"  name="username" style = "width: 50%;" required>
<br/>
      <label for="psw"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="password" style = "width: 50%;" required>
<br/>  
<input type="checkbox" checked="checked" name="remember"> Remember me  
      <button type="submit">Login</button>
      <label>

        
      </label>
    </div>

    <div class="" style="background-color:#f1f1f1">
      <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
      <span class="psw">Forgot <a href="#">password?</a></span>
    </div>
  </form>
</div>

			
		
<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script>	
			

			

			
			
			</td>
			<td></td>
		</thead>
		
	  <tr>
    </tbody>
  </table>

			</div>
		  
		  
			</div>
          <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->
{% endblock %}

product/templates/product/form.html
<button type="button" class="button btn btn-success btn-md" data-toggle="modal" data-target="#myModal"><span>Procced </span></button>
			
			 <!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          
        </div>
        <div class="modal-body">
          <div class="row">
  <div class="col-75">
    <div class="">
	 <form action="{% url 'login:user_login' %}" method="post" class="login-form">{% csrf_token %}
  <div class="imgcontainer">
    <img src='{% static "img/img_avatar2.png" %}'alt="Avatar" class="avatar" height="700px" width="700px"/>
  </div>

  <div class="">
    <label for="uname"><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="username" required>
	<br/>
    <label for="psw"><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="password" required>
	<br/>
    <button type="submit">Login</button>
	<br/>
      <input type="checkbox" checked="checked" name="remember"> Remember me
    </label>
  </div>
<br/>
  <div class="" style="background-color:#f1f1f1">
    <button type="button" class="cancelbtn">Cancel</button>
    <span class="psw">Forgot <a href="#">password?</a></span>
  </div>
</form> 
	
	
	
	
	
      <!--<form action="">
      
        <div class="row">
          <div class="col-50">
            <h3>Billing Address</h3>
            <label for="fname"><i class="fa fa-user"></i> Full Name</label><br/>
            <input type="text" id="fname" name="firstname" placeholder="John M. Doe"><br/>
            <label for="email"><i class="fa fa-envelope"></i> Email</label><br/>
            <input type="text" id="email" name="email" placeholder="john@example.com"><br/>
            <label for="adr"><i class="fa fa-address-card-o"></i> Address</label><br/>
            <input type="text" id="adr" name="address" placeholder="542 W. 15th Street"><br/>
            <label for="city"><i class="fa fa-institution"></i> City</label><br/>
            <input type="text" id="city" name="city" placeholder="New York">
			<br/>
            <div class="row">
              <div class="col-40">
                <label for="state">State</label>
                <input type="text" id="state" name="state" placeholder="NY">
              </div>
              <div class="col-40">
                <label for="zip">Zip</label>
                <input type="text" id="zip" name="zip" placeholder="10001">
              </div>
            </div>
          </div>
        </div>
		<div class="row">
          <div class="col-50">
            <h3>Payment</h3>
            <label for="fname">Accepted Cards</label>
            <div class="icon-container" style="font-size: 50px;">
              <i class="fa fa-cc-visa " style="color:navy;"></i>
              <i class="fa fa-cc-amex" style="color:blue;"></i>
              <i class="fa fa-cc-mastercard" style="color:red;"></i>
              <i class="fa fa-cc-discover" style="color:orange;"></i>
            </div>
            <label for="cname">Name on Card</label><br/>
            <input type="text" id="cname" name="cardname" placeholder="John More Doe"><br/>
            <label for="ccnum">Credit card number</label><br/>
            <input type="text" id="ccnum" name="cardnumber" placeholder="1111-2222-3333-4444"><br/>
            <label for="expmonth">Exp Month</label><br/>
            <input type="text" id="expmonth" name="expmonth" placeholder="September"><br/>
            <div class="row">
              <div class="col-40">
                <label for="expyear">Exp Year</label>
                <input type="text" id="expyear" name="expyear" placeholder="2018">
              </div>
              <div class="col-40">
                <label for="cvv">CVV</label>
                <input type="text" id="cvv" name="cvv" placeholder="352">
              </div>
            </div>
          </div>
          
        </div>
        <label>
          <input type="checkbox" checked="checked" name="sameadr"> Shipping address same as billing
        </label>
		<div class="row">
        <div class="col-40">
		<input type="submit" value="Continue to checkout" class="btn">
        </div>
		</div>
	  </form>-->
    </div>
  </div>
  <div class="col-25">
    <div class="container">
      <h4>Cart <span class="price" style="color:black"><i class="fa fa-shopping-cart"></i> <b>4</b></span></h4>
	  <table class="table" style="width:50%">
      {% for i in cart_detail %}
      <tr>
        
        <td>{{i.product.name}}</td>
        
		<td>{{i|cart_price}}</td>
		
      </tr>
      {% endfor %}
	  
	  </table>
      
      <p>Total <span class="price" style="color:black"><b>$30</b></span></p>
    </div>
  </div>
</div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

product/templates/product/home.html
{% extends 'extends/base.html' %}
{% block content %}
 <div class="row">

        <div class="col-lg-3">

          <h3 class="my-4">All List Of Products</h3>
          <div class="list-group">
		  <ul class="list" style="list-style-type:none">
            <li><a href="#" class="list-group-item active">All</a></li>
            {% for i in category %}
            <li><a href="{% url 'category' i.slug %}">{{i.name}}</a></li>
            {% endfor %}
		  </ul>
          </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">
			<!--<p>{{cart}}  items</p>-->
			
          {% include 'include/slider.html' %}
		  
           <!-- <div class="row">
		  
		    {% for i in category %}
            <div class="col-lg-4 col-md-6 mb-4">
			
			{% for k in i.product_set.all %}
			  <br/>
              <div class="card">
                <a href="#"><img class="card-img-top" src="{{k.pic.url}}" alt="" width="400px" height="150px"/></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">{{k.name}}</a>
                  </h4>
                  <h5>{{k.price}}</h5>
                  <p class="card-text">{{k.description}}</p>				  
				  <a style="margin-left:15%;" href="{% url 'detail' k.id %}" class="btn btn-primary btn-md">Add To Cart</a>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
			  {% endfor %}
			  
            </div>
			
			{% endfor %}
		  
		  
			</div>-->
			
          <!-- /.row -->
		 
		<div class="row">
            <div class="col-md-9">
                <h3></h3>
            </div>
            <div class="col-md-3">
                <!-- Controls -->
               <!-- <div class="controls pull-right hidden-xs">
                    <a class="left fa fa-chevron-left btn btn" href="#carousel-example"
                        data-slide="prev"></a><a class="right fa fa-chevron-right btn" href="#carousel-example"
                            data-slide="next"></a>
                </div>-->
            </div>
        </div>
		<div id="carousel-example" class="carousel slide hidden-xs" data-ride="carousel">
            <!-- Wrapper for slides -->
            <div class="carousel-inner">
                <div class="">
                    <div class="row">
					
                       {% for i in category %}
                        <div class="col-sm-4">
						<div class="item active">
						{% for k in i.product_set.all %}
						  
                            <div class="col-item">
                                <div class="info">
                                    <div class="row">
                                        <div class="price col-md-6">
                                            <h5>{{k.name}}</h5>
                                            <h5 class="price-text-color">Rs. {{k.price}}</h5>
                                        </div>
                                        <div class="rating hidden-sm col-md-6">
                                            <i class="price-text-color fa fa-star"></i>
                                            <i class="price-text-color fa fa-star"></i>
                                        </div>
                                    </div>
                                </div>

                                <div class="photo">
                                    <img class="card-img-top" src="{{k.pic.url}}" alt="" width="400px" height="150px"/>
                                </div>
                                <div class="info">
                                    <div class="separator clear-left">
									
                                        <p class="btn-add">
										
                                            <i class="fa fa-shopping-cart"></i><a href="{% url 'detail' k.id %}" class="hidden-sm">Add to cart</a>
                                        </p>
                                        <p class="btn-details">
                                            <i class="fa fa-list"></i><a href="{% url 'detail' k.id %}" class="hidden-sm">More details</a>
                                        </p>
                                    </div>
                                    <div class="clearfix">
                                    </div>
                                </div>
                            </div>
							
							{% endfor %}
							</div>
                        </div>
						{% endfor %}
                        
                        

                        
                       
                        
                    </div>
                </div>
                
            </div>
				
        </div>
		
		
		
		
        </div>
        <!-- /.col-lg-9 -->
			

      </div>
      <!-- /.row -->
	  
	  
	  
	  
	  
	  
	  
	  
{% endblock %}

product/templates/product/product_category.html
{% extends 'extends/base.html' %}
{% block content %}
 <div class="row">

        <div class="col-lg-3">

          <h3 class="my-4">All List Of Products</h3>
          <div class="list-group">
		  <ul class="list" style="list-style-type:none" >
            <li><a href="{% url 'index' %}" class="list-group-item">All</a></li>
            {% for i in categories %}
					<li><a {% if category.slug == i.slug %}class="active"{% endif %} href="{% url 'category' i.slug %}">{{i.name}}</a></li>
			{% endfor %}
		  </ul>
          </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">
			
			
          {% include 'include/slider.html' %}
		  
          <div class="row">
		  
		    
            <div class="col-lg-4 col-md-6 mb-4">
			
			{% for k in category.product_set.all %}
			  <br/>
              <div class="card">
                <a href="#"><img class="card-img-top" src="{{k.pic.url}}" alt="" width="400px" height="150px"/></a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="#">{{k.name}}</a>
                  </h4>
                  <h5>Rs. {{k.price}}</h5>
                  <p class="card-text">{{k.description}}</p>				  
				  <a style="" href="{% url 'detail' k.id %}" class="btn btn-primary btn-md">Add To Cart</a>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
			  {% endfor %}
			  
            </div>
			
			
			
			
		  
		  
			</div>
          <!-- /.row -->

        </div>
        <!-- /.col-lg-9 -->

      </div>
      <!-- /.row -->
{% endblock %}